"""Content- and filename-based subtitle language detection.

Deterministic, offline, dependency-free heuristics:

1. script analysis of the decoded text (CJK, Hangul, kana, Arabic,
   Hebrew, Greek, Cyrillic, Devanagari…);
2. stop-word scoring for Latin-script languages (en/es/fr/de/it/pt/nl/
   pl/tr/ro/id/fi/sv/da/no/cs/hu/…);
3. file-name language tag fallback (``Movie.eng.srt`` → English).

The detector mirrors the tolerance of the original application: weak or
inconclusive signals yield ``None`` instead of a random guess.
"""

from __future__ import annotations

import re
from pathlib import Path

from opensubtitles_uploader.adapters.media.dataset import bundled_language_index, language_by_tag
from opensubtitles_uploader.domain.model import Language

# ---------------------------------------------------------------------------
# Latin-script languages: iso639-1 -> frequent stop words (lowercase).
# ---------------------------------------------------------------------------
_STOPWORDS: dict[str, frozenset[str]] = {
    "en": frozenset(
        [
            "the",
            "and",
            "of",
            "to",
            "in",
            "is",
            "that",
            "it",
            "you",
            "he",
            "was",
            "for",
            "on",
            "are",
            "with",
            "as",
            "his",
            "they",
            "at",
            "be",
            "this",
            "have",
            "from",
            "or",
            "one",
            "had",
            "by",
            "but",
            "not",
            "what",
            "all",
            "were",
            "we",
            "when",
            "your",
            "can",
            "said",
            "there",
            "use",
            "an",
            "each",
            "which",
            "she",
            "do",
            "how",
            "their",
            "if",
            "will",
            "up",
            "other",
            "about",
            "out",
            "many",
            "then",
            "them",
            "these",
            "so",
            "some",
            "her",
            "would",
            "make",
            "like",
            "him",
            "into",
            "time",
            "has",
            "look",
            "two",
            "more",
            "write",
            "go",
            "see",
            "number",
            "no",
            "way",
            "could",
            "people",
            "than",
            "water",
            "been",
            "call",
            "who",
            "oil",
            "its",
            "now",
            "find",
            "long",
            "down",
            "day",
            "did",
            "get",
            "come",
            "made",
            "may",
            "part",
            "over",
            "new",
            "sound",
            "take",
            "only",
            "little",
            "work",
            "know",
            "place",
            "year",
            "live",
            "me",
            "back",
            "give",
            "most",
            "very",
            "after",
            "thing",
            "our",
            "just",
            "name",
            "good",
            "sentence",
            "man",
            "think",
            "say",
            "great",
            "where",
            "help",
            "through",
            "much",
            "before",
            "line",
            "right",
            "too",
            "mean",
            "old",
            "any",
            "same",
            "tell",
            "boy",
            "follow",
            "came",
            "want",
            "show",
            "also",
            "around",
            "form",
            "three",
            "small",
            "set",
            "put",
            "end",
            "does",
            "another",
            "well",
            "large",
            "must",
            "big",
            "even",
            "such",
            "because",
            "turn",
            "here",
            "why",
            "ask",
            "went",
            "men",
            "read",
            "need",
            "land",
            "different",
            "home",
            "us",
            "move",
            "try",
            "kind",
            "hand",
            "picture",
            "again",
            "change",
            "off",
            "play",
            "spell",
            "air",
            "away",
            "animal",
            "house",
            "point",
            "page",
            "letter",
            "mother",
            "answer",
            "found",
            "study",
            "still",
            "learn",
            "should",
            "america",
            "world",
            "high",
            "every",
            "near",
            "add",
            "food",
            "between",
            "own",
            "below",
            "country",
            "plant",
            "last",
            "school",
            "father",
            "keep",
            "tree",
            "never",
            "start",
            "city",
            "earth",
            "eye",
            "light",
            "thought",
            "head",
            "under",
            "story",
            "saw",
            "left",
            "few",
            "while",
            "along",
            "might",
            "close",
            "something",
            "seem",
            "next",
            "hard",
            "open",
            "example",
            "begin",
            "life",
            "always",
            "those",
            "both",
            "paper",
            "together",
            "got",
            "group",
            "often",
            "run",
            "important",
            "until",
            "children",
            "side",
            "feet",
            "car",
            "mile",
            "night",
            "walk",
            "white",
            "sea",
            "began",
            "grow",
            "took",
            "river",
            "four",
            "carry",
            "state",
            "once",
            "book",
            "hear",
            "stop",
            "without",
            "second",
            "late",
            "miss",
            "idea",
            "enough",
            "eat",
            "face",
            "watch",
            "far",
            "indian",
            "really",
            "almost",
            "let",
            "above",
            "girl",
            "sometimes",
            "mountain",
            "cut",
            "young",
            "talk",
            "soon",
            "list",
            "song",
            "being",
            "leave",
            "family",
            "it's",
        ]
    ),
    "es": frozenset(
        [
            "el",
            "la",
            "los",
            "las",
            "de",
            "que",
            "y",
            "en",
            "un",
            "una",
            "es",
            "por",
            "con",
            "no",
            "a",
            "su",
            "al",
            "lo",
            "como",
            "más",
            "pero",
            "sus",
            "le",
            "ya",
            "o",
            "este",
            "sí",
            "porque",
            "esta",
            "entre",
            "cuando",
            "muy",
            "sin",
            "sobre",
            "también",
            "me",
            "hasta",
            "hay",
            "donde",
            "quien",
            "desde",
            "todo",
            "nos",
            "durante",
            "todos",
            "uno",
            "les",
            "ni",
            "contra",
            "otros",
            "ese",
            "eso",
            "ante",
            "ellos",
            "e",
            "esto",
            "mí",
            "antes",
            "algunos",
            "qué",
            "unos",
            "yo",
            "otro",
            "otras",
            "otra",
            "él",
            "tanto",
            "esa",
            "estos",
            "mucho",
            "quienes",
            "nada",
            "muchos",
            "cual",
            "poco",
            "ella",
            "estar",
            "estas",
            "algunas",
            "algo",
            "nosotros",
            "mi",
            "mis",
            "tú",
            "te",
            "ti",
            "tu",
            "tus",
            "ellas",
            "nosotras",
            "vosotros",
            "vosotras",
            "os",
            "mío",
            "mía",
            "míos",
            "mías",
            "tuyo",
            "tuya",
            "suyo",
            "suya",
            "nuestro",
            "nuestra",
            "vuestro",
            "vuestra",
        ]
    ),
    "fr": frozenset(
        [
            "le",
            "la",
            "les",
            "de",
            "des",
            "et",
            "un",
            "une",
            "du",
            "que",
            "est",
            "en",
            "il",
            "a",
            "ce",
            "qui",
            "vous",
            "pour",
            "pas",
            "sur",
            "ne",
            "aux",
            "par",
            "avec",
            "dans",
            "se",
            "sont",
            "sa",
            "son",
            "mais",
            "ou",
            "comme",
            "au",
            "si",
            "tout",
            "cette",
            "été",
            "je",
            "il",
            "elle",
            "nous",
            "ils",
            "elles",
            "tu",
            "te",
            "toi",
            "on",
            "ça",
        ]
    ),
    "de": frozenset(
        [
            "der",
            "die",
            "das",
            "und",
            "ist",
            "den",
            "von",
            "zu",
            "mit",
            "sich",
            "des",
            "im",
            "dem",
            "nicht",
            "ein",
            "eine",
            "als",
            "auch",
            "es",
            "an",
            "er",
            "sie",
            "war",
            "für",
            "auf",
            "wird",
            "bei",
            "ins",
        ]
    ),
    "it": frozenset(
        [
            "il",
            "lo",
            "la",
            "gli",
            "le",
            "di",
            "che",
            "e",
            "un",
            "una",
            "per",
            "con",
            "non",
            "in",
            "ha",
            "da",
            "si",
            "mi",
            "ti",
            "tu",
            "noi",
            "voi",
            "loro",
            "questo",
            "questa",
            "sono",
            "come",
            "più",
            "è",
        ]
    ),
    "pt": frozenset(
        [
            "o",
            "a",
            "os",
            "as",
            "de",
            "que",
            "e",
            "um",
            "uma",
            "para",
            "em",
            "não",
            "é",
            "com",
            "do",
            "da",
            "por",
            "mais",
            "se",
            "eu",
            "você",
            "ele",
            "ela",
            "nós",
            "eles",
            "elas",
            "isso",
            "isto",
            "esse",
            "essa",
            "este",
            "esta",
        ]
    ),
    "nl": frozenset(
        [
            "de",
            "het",
            "een",
            "van",
            "en",
            "is",
            "dat",
            "op",
            "te",
            "zijn",
            "ik",
            "hij",
            "zij",
            "wij",
            "jullie",
            "met",
            "niet",
            "maar",
            "ook",
            "als",
            "aan",
            "dan",
            "er",
        ]
    ),
    "pl": frozenset(
        [
            "i",
            "w",
            "nie",
            "na",
            "to",
            "się",
            "z",
            "do",
            "jest",
            "że",
            "się",
            "o",
            "co",
            "jak",
            "ale",
            "po",
            "za",
            "przez",
            "oraz",
        ]
    ),
    "tr": frozenset(
        [
            "ve",
            "bir",
            "bu",
            "ben",
            "sen",
            "o",
            "biz",
            "siz",
            "onlar",
            "için",
            "de",
            "da",
            "ile",
            "ne",
            "gibi",
            "ama",
            "çok",
        ]
    ),
    "ro": frozenset(
        [
            "și",
            "de",
            "la",
            "un",
            "o",
            "în",
            "nu",
            "este",
            "cu",
            "pe",
            "mai",
            "dar",
            "pentru",
            "că",
            "și",
            "ce",
            "sau",
            "dintre",
        ]
    ),
    "id": frozenset(
        [
            "dan",
            "yang",
            "di",
            "ke",
            "ini",
            "itu",
            "aku",
            "kamu",
            "dia",
            "kami",
            "kita",
            "mereka",
            "dengan",
            "untuk",
            "tidak",
            "ada",
            "saya",
        ]
    ),
    "fi": frozenset(
        [
            "ja",
            "on",
            "ei",
            "se",
            "että",
            "oli",
            "ovat",
            "hän",
            "minä",
            "sinä",
            "me",
            "te",
            "he",
            "mutta",
            "kun",
            "niin",
        ]
    ),
    "sv": frozenset(
        [
            "och",
            "att",
            "det",
            "som",
            "en",
            "är",
            "inte",
            "har",
            "jag",
            "du",
            "han",
            "hon",
            "vi",
            "de",
            "med",
            "för",
            "om",
        ]
    ),
    "da": frozenset(
        [
            "og",
            "at",
            "det",
            "er",
            "ikke",
            "jeg",
            "du",
            "han",
            "hun",
            "vi",
            "de",
            "med",
            "for",
            "som",
            "en",
        ]
    ),
    "no": frozenset(
        [
            "og",
            "at",
            "det",
            "er",
            "ikke",
            "jeg",
            "du",
            "han",
            "hun",
            "vi",
            "de",
            "med",
            "for",
            "som",
            "en",
        ]
    ),
    "cs": frozenset(
        [
            "a",
            "se",
            "na",
            "je",
            "že",
            "to",
            "v",
            "o",
            "s",
            "z",
            "pro",
            "ale",
            "jako",
            "jsou",
            "jsem",
            "já",
            "ty",
            "oni",
        ]
    ),
    "hu": frozenset(
        [
            "és",
            "a",
            "az",
            "hogy",
            "nem",
            "egy",
            "van",
            "ez",
            "is",
            "én",
            "te",
            "ő",
            "mi",
            "ti",
            "ők",
            "de",
        ]
    ),
    "el": frozenset(
        ["και", "το", "τη", "να", "που", "με", "για", "δεν", "είναι", "ο", "η", "του", "την", "από"]
    ),
    "ru": frozenset(
        [
            "и",
            "в",
            "не",
            "на",
            "я",
            "что",
            "он",
            "с",
            "как",
            "это",
            "она",
            "по",
            "но",
            "они",
            "мы",
            "вы",
            "его",
            "её",
        ]
    ),
    "uk": frozenset(
        [
            "і",
            "в",
            "не",
            "на",
            "я",
            "що",
            "він",
            "з",
            "як",
            "це",
            "вона",
            "по",
            "але",
            "вони",
            "ми",
            "ви",
            "його",
            "її",
        ]
    ),
    "bg": frozenset(
        [
            "и",
            "в",
            "не",
            "на",
            "аз",
            "той",
            "тя",
            "то",
            "с",
            "като",
            "това",
            "за",
            "но",
            "те",
            "ние",
            "вие",
        ]
    ),
    "sr": frozenset(
        [
            "и",
            "у",
            "не",
            "на",
            "ја",
            "он",
            "она",
            "оно",
            "што",
            "је",
            "са",
            "као",
            "овај",
            "за",
            "али",
            "они",
        ]
    ),
    "ar": frozenset(
        [
            "في",
            "من",
            "على",
            "إلى",
            "عن",
            "أن",
            "إن",
            "هذا",
            "هذه",
            "كان",
            "كانت",
            "لا",
            "ما",
            "هو",
            "هي",
            "أنا",
            "نحن",
        ]
    ),
    "he": frozenset(
        ["של", "על", "את", "זה", "אני", "הוא", "היא", "אנחנו", "אתם", "אתן", "לא", "כן", "עם"]
    ),
    "hi": frozenset(
        [
            "और",
            "का",
            "की",
            "में",
            "है",
            "था",
            "थी",
            "नहीं",
            "यह",
            "वह",
            "मैं",
            "हम",
            "आप",
            "पर",
            "से",
            "को",
            "एक",
        ]
    ),
    "zh": frozenset(
        [
            "的",
            "了",
            "是",
            "在",
            "我",
            "你",
            "他",
            "她",
            "我们",
            "你们",
            "他们",
            "有",
            "不",
            "这",
            "那",
            "吗",
            "呢",
        ]
    ),
    "ja": frozenset(
        ["の", "は", "を", "に", "が", "と", "で", "です", "ます", "私", "あなた", "それ", "これ"]
    ),
    "ko": frozenset(
        ["의", "에", "는", "이", "가", "을", "를", "입니다", "나", "당신", "그", "이것"]
    ),
}

# iso639-1 fallbacks not necessarily present in the bundled dataset.
_NAME_FALLBACK: dict[str, str] = {"zh": "Chinese", "ja": "Japanese", "ko": "Korean"}

# Script classifiers operating on single characters.
_CJK = re.compile(r"[\u4e00-\u9fff]")
_HIRAGANA = re.compile(r"[\u3040-\u309f]")
_KATAKANA = re.compile(r"[\u30a0-\u30ff]")
_HANGUL = re.compile(r"[\uac00-\ud7af]")
_ARABIC = re.compile(r"[\u0600-\u06ff\u0750-\u077f]")
_HEBREW = re.compile(r"[\u0590-\u05ff]")
_GREEK = re.compile(r"[\u0370-\u03ff\u1f00-\u1fff]")
_CYRILLIC = re.compile(r"[\u0400-\u04ff]")
_DEVANAGARI = re.compile(r"[\u0900-\u097f]")
_THAI = re.compile(r"[\u0e00-\u0e7f]")

_FILENAME_TAG_RE = re.compile(
    r"\.(?P<tag>[a-z]{2,3})(?:[-_][a-z0-9]{2,8})?(?=\.[a-z]{2,4}$|$)", re.IGNORECASE
)

_DECODE_ATTEMPTS = ("utf-8-sig", "utf-16", "latin-1")


def _read_head(path: Path, limit: int = 120_000) -> str:
    try:
        with path.open("rb") as handle:
            raw = handle.read(limit)
    except OSError:
        return ""
    for encoding in _DECODE_ATTEMPTS:
        try:
            return raw.decode(encoding)
        except (UnicodeDecodeError, LookupError):
            continue
    return ""


def _score(text: str) -> tuple[str, float] | None:
    """Return (iso639-1, score) for the strongest language signal."""
    total = max(len(text), 1)

    def ratio(regex: re.Pattern[str]) -> float:
        hits = sum(1 for _ in regex.finditer(text))
        return hits / total

    # ---- script-based languages -----------------------------------------
    kana = ratio(_HIRAGANA) + ratio(_KATAKANA)
    if kana > 0.005:
        return "ja", kana
    samples = {
        "el": ratio(_GREEK),
        "ar": ratio(_ARABIC),
        "he": ratio(_HEBREW),
        "hi": ratio(_DEVANAGARI),
        "th": ratio(_THAI),
        "ko": ratio(_HANGUL),
        "zh": ratio(_CJK),
        "ru": ratio(_CYRILLIC),
    }
    best_script = max(samples, key=lambda k: samples[k])
    if samples[best_script] > 0.02:
        return best_script, samples[best_script]

    # ---- stop-word scoring for Latin scripts -----------------------------
    words = re.findall(r"[a-zà-ÿ]+", text.lower())
    if not words:
        return None
    best: tuple[str, float] | None = None
    for iso, stops in _STOPWORDS.items():
        if iso in {"el", "ru", "uk", "bg", "sr", "ar", "he", "hi", "zh", "ja", "ko"}:
            continue  # covered by script detection
        hits = sum(1 for w in words if w in stops)
        score = hits / len(words)
        if best is None or score > best[1]:
            best = (iso, score)
    if best and best[1] >= 0.12:
        return best
    return None


def _resolve(iso639_1: str) -> Language:
    index = bundled_language_index()
    language = index.get(iso639_1)
    if language is not None:
        return language
    return Language(code="", iso639_1=iso639_1, name=_NAME_FALLBACK.get(iso639_1, iso639_1))


class HeuristicLanguageDetector:
    """Default :class:`LanguageDetector` implementation."""

    def detect(self, subtitle_path: Path) -> Language | None:
        path = Path(subtitle_path)
        text = _read_head(path)
        detected = _score(text) if text else None
        if detected:
            return _resolve(detected[0])

        # Filename approach ("my.movie.eng.srt" or "my.movie.en.srt").
        match = _FILENAME_TAG_RE.search(path.stem)
        if match:
            language = language_by_tag(match.group("tag"))
            if language:
                return language
        # Whole-stem fallback: "movie.english.srt" would not match above,
        # try a looser tag search on the full name.
        match = re.search(
            r"\.([a-z]{2,8})\.(?:srt|sub|ass|ssa|smi|txt|mpl)$", path.name, re.IGNORECASE
        )
        if match:
            language = language_by_tag(match.group(1))
            if language:
                return language
        return None
